
// This file has been generated by the GUI designer. Do not modify.
namespace JamOween
{
	public partial class StartingWindow
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.Image image254;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.RadioButton radbtn_werewolf;
		private global::Gtk.Button button5;
		private global::Gtk.Button button6;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button7;
		private global::Gtk.RadioButton radbtn_vampire;
		private global::Gtk.HSeparator hseparator2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget JamOween.StartingWindow
			this.Name = "JamOween.StartingWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("StartingWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child JamOween.StartingWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			this.vbox3.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox1]));
			w1.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image254 = new global::Gtk.Image ();
			this.image254.Name = "image254";
			this.image254.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.startback.png");
			this.vbox3.Add (this.image254);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.image254]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.hbox4.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hseparator3]));
			w3.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.radbtn_werewolf = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Werewolf Pack"));
			this.radbtn_werewolf.CanFocus = true;
			this.radbtn_werewolf.Name = "radbtn_werewolf";
			this.radbtn_werewolf.DrawIndicator = true;
			this.radbtn_werewolf.UseUnderline = true;
			this.radbtn_werewolf.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox4.Add (this.radbtn_werewolf);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.radbtn_werewolf]));
			w4.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Easy");
			this.hbox4.Add (this.button5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button5]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox4]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("Medium");
			this.hbox2.Add (this.button6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Hard");
			this.hbox3.Add (this.button7);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button7]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.radbtn_vampire = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Vampire Den"));
			this.radbtn_vampire.CanFocus = true;
			this.radbtn_vampire.Name = "radbtn_vampire";
			this.radbtn_vampire.DrawIndicator = true;
			this.radbtn_vampire.UseUnderline = true;
			this.radbtn_vampire.Group = this.radbtn_werewolf.Group;
			this.hbox3.Add (this.radbtn_vampire);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.radbtn_vampire]));
			w9.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.hbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hseparator2]));
			w10.Position = 2;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w11.Position = 2;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 806;
			this.DefaultHeight = 739;
			this.Show ();
			this.button5.Clicked += new global::System.EventHandler (this.EasyGameStart);
			this.button6.Clicked += new global::System.EventHandler (this.MediumGameStart);
		}
	}
}
