
// This file has been generated by the GUI designer. Do not modify.
namespace JamOween
{
	public partial class Winner
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label lb_win1;
		private global::Gtk.Label lb_finalscore;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ToggleButton btn_quit;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.ToggleButton btn_new;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget JamOween.Winner
			this.Name = "JamOween.Winner";
			this.Title = global::Mono.Unix.Catalog.GetString ("Winner");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child JamOween.Winner.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lb_win1 = new global::Gtk.Label ();
			this.lb_win1.Name = "lb_win1";
			this.lb_win1.LabelProp = global::Mono.Unix.Catalog.GetString ("Congratulation you won");
			this.vbox1.Add (this.lb_win1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lb_win1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lb_finalscore = new global::Gtk.Label ();
			this.lb_finalscore.Name = "lb_finalscore";
			this.lb_finalscore.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox1.Add (this.lb_finalscore);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lb_finalscore]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btn_quit = new global::Gtk.ToggleButton ();
			this.btn_quit.CanFocus = true;
			this.btn_quit.Name = "btn_quit";
			this.btn_quit.UseUnderline = true;
			this.btn_quit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.hbox1.Add (this.btn_quit);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btn_quit]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.hbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator1]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btn_new = new global::Gtk.ToggleButton ();
			this.btn_new.CanFocus = true;
			this.btn_new.Name = "btn_new";
			this.btn_new.UseUnderline = true;
			this.btn_new.Label = global::Mono.Unix.Catalog.GetString ("Play Again?");
			this.hbox1.Add (this.btn_new);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btn_new]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 174;
			this.DefaultHeight = 104;
			this.Show ();
			this.btn_new.Clicked += new global::System.EventHandler (this.PlayAgain);
		}
	}
}
