
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Image img_TL;
	private global::Gtk.Image img_TM;
	private global::Gtk.Image img_TR;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Image img_ML;
	private global::Gtk.Image img_MM;
	private global::Gtk.Image img_MR;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Image img_BL;
	private global::Gtk.Image img_BM;
	private global::Gtk.Image img_BR;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.img_TL = new global::Gtk.Image ();
		this.img_TL.Name = "img_TL";
		this.img_TL.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox3.Add (this.img_TL);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.img_TL]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.img_TM = new global::Gtk.Image ();
		this.img_TM.Name = "img_TM";
		this.img_TM.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox3.Add (this.img_TM);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.img_TM]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.img_TR = new global::Gtk.Image ();
		this.img_TR.Name = "img_TR";
		this.img_TR.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox3.Add (this.img_TR);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.img_TR]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.img_ML = new global::Gtk.Image ();
		this.img_ML.Name = "img_ML";
		this.img_ML.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox4.Add (this.img_ML);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.img_ML]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.img_MM = new global::Gtk.Image ();
		this.img_MM.Name = "img_MM";
		this.img_MM.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox4.Add (this.img_MM);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.img_MM]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.img_MR = new global::Gtk.Image ();
		this.img_MR.Name = "img_MR";
		this.img_MR.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox4.Add (this.img_MR);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.img_MR]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.img_BL = new global::Gtk.Image ();
		this.img_BL.Name = "img_BL";
		this.img_BL.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox5.Add (this.img_BL);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.img_BL]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.img_BM = new global::Gtk.Image ();
		this.img_BM.Name = "img_BM";
		this.img_BM.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox5.Add (this.img_BM);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.img_BM]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.img_BR = new global::Gtk.Image ();
		this.img_BR.Name = "img_BR";
		this.img_BR.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("JamOween.img.Warewolf Template.png");
		this.hbox5.Add (this.img_BR);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.img_BR]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
